### ISSUE TITLE
Issues with hardware SPI mode

### ISSUE THREAD

**Issue by EricBayer** [adafruit/Adafruit_DotStar_Pi#1]
The hardware SPI mode code does wacky things when brightness is not 0 (usually leaves a green pixel, but it flickers during updates.)  This is because you're transmitting the raw mode IOCTL structures as data rather than the header and footer payload.  Here's the fix:

https://gist.github.com/EricBayer/d1be199ec684c425c0a8

**Comment by PaintYourDragon** [comment]
Incorporated into latest commit. Thanks for pointing this out!
