### ISSUE TITLE
Color output is wrong

### ISSUE THREAD

**Issue by chiefcll** [adafruit/Adafruit_DotStar_Pi#11]
strip.setPixelColor(pixel, 0,0,255) -> Green (should be Blue)
strip.setPixelColor(pixel, 0,255,0) -> Red (should be Green)
strip.setPixelColor(pixel, 255,0,0) -> Blue (should be Red)

**Comment by PaintYourDragon** [comment]
Recent versions of the code accept an "order" keyword in the declaration, e.g.:
`strip = Adafruit_DotStar(60, order='gbr')`
Color order has been known to change between manufacturers and even different production runs, so there is no One Canonical Best Color Order to use as a default; the default that's in there ('bgr') is whatever the version of DotStar strips I was using at the time the feature was added.
