### ISSUE TITLE
Noobie question

### ISSUE THREAD

**Issue by philspitlerSF** [adafruit/Adafruit_DotStar_Pi#12]
hi, I am new to the pi and Python and get this error when trying to run the strandtst.py.

I am using a piZero. Also I see there is an SPI and a bitbang mode, where do I switch the mode?

Also, am I correct to run the code by typing "python strandtest.py"

Thanks.

> pi@raspberrypi:~/LED/Adafruit $ python strandtest.py
> Can't open /dev/mem (try 'sudo')
> Traceback (most recent call last):
>   File "strandtest.py", line 28, in <module>
>     strip.begin()           # Initialize pins for output
> SystemError: error return without exception set

**Comment by hairyhenderson** [comment]
@philspitlerSF - try this command instead:

``` console
$ sudo python strandtest.py
```

The `sudo` command tells Linux to run the following command as the root user, which gives the command additional privileges that it wouldn't otherwise have (such as access to `/dev/mem`, as you see in the error).

**Comment by d4nc3rmon** [comment]
I am using a Rapsberry Pi 3 and am having this same error. When I use sudo however the error doesn't come up, instead everything just sits idly. Nothing happens on the board,lights, pi, or on the terminal line. There's not even a "$" so I can type more code.

**Comment by PaintYourDragon** [comment]
If nothing in the console, that means the code's running OK. If the DotStars aren't lighting, could be wired to the wrong pins (clock & data may be reversed, or you might be counting physical pin numbers -- code wants Broadcom GPIO pin numbers).
