### ISSUE TITLE
Works in Python 3?

### ISSUE THREAD

**Issue by stuff4me** [adafruit/Adafruit_DotStar_Pi#13]
Will this library/module work in Python 3.x? I got it working to an extent in 2.7, I was getting the error about SystemError: error return without exception set. I will run it as sudo and see if that executes the code correctly.

Why I ask if this works on Python 3.x is because I have written my gui in 3.x and would like to keep it in 3.x to kind of future proof my program.

Is there a way to install this library/module into Python 3.x or does it need to be rewritten?

**Comment by lucg** [comment]
Was this closed because a solution was found? If so, what is it?

**Comment by ayman** [comment]
[The APA102_Pi library](https://github.com/tinue/APA102_Pi) is pure python and works in py3.
