### ISSUE TITLE
Memory leak in getPixelColor?

### ISSUE THREAD

**Issue by casoich** [adafruit/Adafruit_DotStar_Pi#15]
- Platform/operating system (i.e. Raspberry Pi with Raspbian operating system,
  Windows 32-bit, Windows 64-bit, Mac OSX 64-bit, etc.):  **Raspberry Pi with Jessie operating system**

- Python version (run `python -version` or `python3 -version`):  **Python 2.7.9 (default, Mar  8 2015, 00:52:26) **

- Error message you are receiving, including any Python exception traces:  **Memory leak in _PyObject *getPixelColor(DotStarObject *self, PyObject *arg)_ * **

- List the steps to reproduce the problem below (if possible attach code or commands
  to run): **LIST REPRO STEPS BELOW**
A routine that uses the _getPixelColor_ function will cause an increase in memory usage in the `python` process, eventually causing the process to bail out. The snippet below can be altered by commenting the getPixelColor line in and out, and using `top` to see the process memory heap.
```
def addToPixelColor(pixel,color):
	# pixColor =strip.getPixelColor(pixel)
	orig_r=pixColor  >>16
	orig_g=pixColor  >> 8 & 0xff
	orig_b=pixColor & 0x000000ff
	add_r=color  >>16
	add_g=color  >> 8 & 0xff
	add_b=color & 0x000000ff
	strip.setPixelColor(pixel,min(orig_r+add_r,255),min(orig_g+add_g,255),min(orig_b+add_b,255))
```
Included is the entire .py script if you wanted to try it for yourself. 
If you run it, try `python pixelmatrix.py flurry`
[pixelmatrix.py.zip](https://github.com/adafruit/Adafruit_DotStar_Pi/files/565472/pixelmatrix.py.zip)

**Comment by casoich** [comment]
I now believe the leak to be in the .Color method (line 525 in the dotstar.c library) here:

```
// Given separate R, G, B, return a packed 32-bit color.
// Meh, mostly here for parity w/Arduino library.
static PyObject *Color(DotStarObject *self, PyObject *arg) {
    uint8_t   r, g, b;
    PyObject *result;

    if(!PyArg_ParseTuple(arg, "bbb", &r, &g, &b)) return NULL;

    result = Py_BuildValue("I", (r << 16) | (g << 8) | b);
    Py_INCREF(result);
    return result;
}
```

I don't know enough about C to know what's leaking, but I have an equivalent method in python, that does not leak:

```
def RGBto32(rIn,gIn,bIn):
    pass
    return ( ( rIn << 16 ) | ( gIn << 8 ) | bIn )
```

(note the `pass` is in there just to allow me to collapse the function in Sublime Text. :-) )

**Comment by PaintYourDragon** [comment]
Yep, that seemed to fix it. Thanks for spotting!
