### ISSUE TITLE
fatal error: bcm_host.h: No such file or directory

### ISSUE THREAD

**Issue by trailhead** [adafruit/Adafruit_DotStar_Pi#19]
On a new install from 2017-09-07-raspbian-stretch.img on a Pi 2b v1.1.
I've installed libsdl2 using apt-get, but other than that it's a pretty fresh install.  Looks like including bcm_host.h was just added a few days ago.

pi@lightwall:~/Adafruit_DotStar_Pi $ sudo python setup.py install
running install
running build
running build_ext
building 'dotstar' extension
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-9xgeTe/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c dotstar.c -o build/temp.linux-armv7l-2.7/dotstar.o
dotstar.c:62:22: fatal error: bcm_host.h: No such file or directory
 #include <bcm_host.h>

**Comment by PaintYourDragon** [comment]
Fixed in setup.py now. You'll get some compiler warnings, but these can be ignored.

Will also need to apt-get python-dev (for the library) and python-imaging (for the examples).
