### ISSUE TITLE
SPI when brightness isn't maximum is incredibly slow

### ISSUE THREAD

**Issue by EricBayer** [adafruit/Adafruit_DotStar_Pi#2]
If the brightness is max, SPI is quite fast.  All the writes slow the whole thing down.  Bitbanging is always really fast.  As SPI is a more system friendly way, I wanted this to work fast.  To accomplish this, I allocated a secondary buffer and I fill it first and then transmit it with raw_write.  This appears to work very fast.  NOTE: This has the other SPI fix mixed in too.

https://gist.github.com/EricBayer/67dc79cdc65ce2247f73

**Comment by PaintYourDragon** [comment]
Incorporated into latest commit, w/attribution. Thanks for fixing this up!
