### ISSUE TITLE
strandtest.py identifies wrong pins as hardware SPI

### ISSUE THREAD

**Issue by robotskirts** [adafruit/Adafruit_DotStar_Pi#8]
Line 21 of strandtest.py says rpi spi pins 11,12 while dotstar.c has 10,11 (which I believe is the correct one)

**Comment by tdicola** [comment]
Oh nice thanks for catching that, yeah looking at the Pi GPIO mapping 10, 11 is what we want: http://elinux.org/RPi_Low-level_peripherals  Thanks!
